### PR TITLE
Example dependencies.io implementation

### PR DESCRIPTION
**Pull request by davegaeddert**
Here's a basic start! I didn't try to look for all of the dependencies you might be wanting to use it with, but I'm guessing this was roughly what you were wanting to do?

Here's an example of a PR created by deps: https://github.com/dropseed/cairo-windows/pull/1

Let me know what you think.

### CODE REVIEW

**Comment by stuaxo** [comment]
Hi,
   This doesn't look quite right, it's confusing pycairo (the binding) with cairo (the shared library).

So it's tried to update cairo to 1.19.1 when the highest version is 1.17.2
https://www.cairographics.org/

I want it to generate a patch to update the C dependencies, something like the bit of the following PR

https://github.com/stuaxo/cairo-windows/pull/1/commits/76335f8cabd064247efb0855b5af965456c624b1

That makes these changes:

CAIRO_VERSION=cairo-1.15.12 -> CAIRO_VERSION=cairo-1.17.2
PIXMAN_VERSION=pixman-0.34.0 -> PIXMAN_VERSION=pixman-0.40.0
LIBPNG_VERSION=libpng-1.6.35 -> LIBPNG_VERSION=libpng-1.6.37
FREETYPE_VERSION=freetype-2.9.1 -> FREETYPE_VERSION=freetype-2.10.2

Will dependencies.io work when I change  `runs-on` to   `runs-on: windows-latest` since this is about building windows versions of these shared libraries / dlls ?

**Comment by davegaeddert** [comment]
@stuaxo my mistake -- I just picked the first cairo repo I found as an example. Is this the right repo to track https://github.com/freedesktop/cairo? It doesn't look like they tag any of the releases, which is the easiest way to find the available versions... Did you have a something else in mind for finding the available versions of cairo?

I went ahead and tried a setup for pixman, libpng, and freetype. You can see those in the PR here and here are the PRs it would have created (I reverted your update commit on my branch just so you could see how dependencies.io would have done it): https://github.com/dropseed/cairo-windows/pulls

edit: We don't currently release a binary to run this on Windows, but probably could. I'm not sure it matters here at the moment since we can perform these kinds of updates regardless of OS.

**Comment by stuaxo** [comment]
Wow, tnanks, this is very cool.

It looks like the github mirror for cairo doesn't have tags, but has branches instead,
luckily the upstream repos for cairo and pixman do seem to have tags
git://anongit.freedesktop.org/git/cairo
git://anongit.freedesktop.org/git/pixman

I'll merge this + update to the above repos and see how things go :)

**Comment by stuaxo** [comment]
Since my clone is temporary, I'm going to do some jiggery pokery on the main branch, so that it is based on the older version, then I should see dependencies.io do its thing.

**Comment by stuaxo** [comment]
Cheers, finally pushing this.

Deleting the old branches so deps can do it's thing.

**Pull request merged**
